version: "3.8"

services:
  d_minio01:
    image: minio/minio:latest
    container_name: d_minio01
    ports:
      - "20100:9000"     # MinIO API
      - "20101:9001"     # MinIO Console
    environment:
      MINIO_ROOT_USER: datalake
      MINIO_ROOT_PASSWORD: datalake
    command: server /data --console-address ":9001"
    volumes:
      - /mnt/Vault/Homelab/Portainer/Stacks/Datalake/dev/infra/Minio/data:/data
    restart: unless-stopped
    
  server:
    image: unitycatalog/unitycatalog:latest
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - /mnt/Vault/Homelab/Portainer/Stacks/Datalake/dev/infra/UnityCatalog/server/conf:/home/unitycatalog/etc/conf
      - /mnt/Vault/Homelab/Portainer/Stacks/Datalake/dev/infra/UnityCatalog/server/data:/home/unitycatalog/etc/data
      - /mnt/Vault/Homelab/Portainer/Stacks/Datalake/dev/infra/UnityCatalog/server/db:/home/unitycatalog/etc/db
      - /mnt/Vault/Homelab/Portainer/Stacks/Datalake/dev/infra/UnityCatalog/server/logs:/home/unitycatalog/etc/logs
    restart: unless-stopped
      
  d_unitycatalog-ui:
    image: unitycatalog-ui:latest
    container_name: d_unitycatalog-ui
    ports:
      - "20201:3000"
    depends_on:
      - server
    restart: unless-stopped
  
  d_code-server:
    image: custom-code-server:1.0.3
    container_name: d_code-server
    environment:
      - PASSWORD=yourpassword
      - PUID=1000
      - PGID=1000
    command: --bind-addr 0.0.0.0:20285
    network_mode: host
    volumes:
      - /mnt/Vault/Homelab/Portainer/Stacks/Datalake/dev/infra/vscode/projects:/home/coder/project
    restart: unless-stopped
  
  d_spark-master:
    image: apache/spark:latest
    container_name: d_spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host 192.168.1.3
      --port 20277
      --webui-port 18080
    network_mode: host
    restart: unless-stopped

  d_spark-worker:
    image: apache/spark:latest
    container_name: d_spark-worker
    command: >
      bash -c "
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://192.168.1.3:20277
      "
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    network_mode: host
    depends_on:
      - d_spark-master
    restart: unless-stopped